import { Box, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../Components/layout'
import styles from '../styles/Home.module.css'


export default function Home () {
  return (
    <Layout>
      <Box className={styles.container}>
        <Head>
          <title>SilverSea</title>
          <meta name='description' content='Generated by create next app' />
          <link rel="https://cdn.rawgit.com/mfd/7c7a915eb31474cc8c6a65066a4c4dc3/raw/f0f2fb94c21dea904812a53e0eb6cf0bc87f3754/GTWalsheimPro.css"></link>
        </Head>
        <Box>
          
        </Box>
      </Box>
    </Layout>
  )
}
